#SAMPLES=['A', 'B', 'C']

import os
# read config info into this namespace
configfile: "config.yaml"
  
rule all:
  input:
    #expand("data/samples/{sample}.fastq", sample=SAMPLES)
    expand("data/samples/{sample}.fastq", sample=config["SAMPLES"])

rule bwa_map:
  input:
    "data/genome.fa",
    "data/samples/{sample}.fastq"
  output:
    "mapped_reads/{sample}.bam"
  shell:
    "bwa mem {input} | samtools view -Sb - > {output}"
